import CookbookApp from "../components/CookbookApp"; 

import Logging from "../assets/docs/AgentObservability/Logging.md?raw";
import Tracing from "../assets/docs/AgentObservability/Tracing.md?raw";
import Metrics from "../assets/docs/AgentObservability/Metrics.md?raw";
import Monitoring from "../assets/docs/AgentObservability/Monitoring.md?raw";
import Langfuse from "../assets/docs/AgentObservability/Langfuse.md?raw";
import LangSmith from "../assets/docs/AgentObservability/LangSmith.md?raw";
import OpenTelemetry from "../assets/docs/AgentObservability/OpenTelemetry.md?raw";
import CostTracking from "../assets/docs/AgentObservability/CostTracking.md?raw";
import Debugging from "../assets/docs/AgentObservability/Debugging.md?raw";
import ProductionMonitoring from "../assets/docs/AgentObservability/ProductionMonitoring.md?raw";

const AgentObservability=[
{
  id: "logging",
  category: "Observability",
  title: "Logging",
  difficulty: "Beginner",
  time: "~10 min",
  description:
    "Learn how logging captures AI Agent events, tool executions, errors, and workflow activities to simplify debugging, auditing, and system analysis.",

  tags: [
    "logging",
    "logs",
    "debugging",
    "monitoring",
    "events",
    "audit",
    "observability"
  ],

  concept: Logging,

  steps: [
    {
      label: "Capture Events",
      icon: "📝",
      detail:
        "Record important events such as user requests, agent decisions, tool calls, and workflow execution."
    },
    {
      label: "Store Logs",
      icon: "💾",
      detail:
        "Save logs in a centralized location for future analysis and auditing."
    },
    {
      label: "Track Errors",
      icon: "⚠️",
      detail:
        "Log failures, exceptions, retries, and unexpected behaviors during execution."
    },
    {
      label: "Analyze Activity",
      icon: "🔍",
      detail:
        "Review logs to understand execution flow and identify operational issues."
    },
    {
      label: "Support Debugging",
      icon: "🛠️",
      detail:
        "Use logs to diagnose problems and improve workflow reliability."
    },
    {
      label: "Maintain Audit Trail",
      icon: "📊",
      detail:
        "Keep historical records for compliance, governance, and production support."
    }
  ],

  code: ""
},
{
  id: "metrics",
  category: "Observability",
  title: "Metrics",
  difficulty: "Intermediate",
  time: "~10 min",
  description:
    "Learn how metrics quantify AI Agent performance by measuring response time, success rate, resource utilization, costs, and overall system health.",

  tags: [
    "metrics",
    "performance",
    "monitoring",
    "kpis",
    "analytics",
    "observability",
    "measurement"
  ],

  concept: Metrics,

  steps: [
    {
      label: "Define Metrics",
      icon: "📋",
      detail:
        "Identify key performance indicators such as latency, throughput, success rate, token usage, and cost."
    },
    {
      label: "Collect Data",
      icon: "📥",
      detail:
        "Gather metrics from agent executions, tool calls, APIs, and infrastructure components."
    },
    {
      label: "Analyze Trends",
      icon: "📊",
      detail:
        "Monitor changes in performance over time to identify improvements or degradation."
    },
    {
      label: "Detect Anomalies",
      icon: "🚨",
      detail:
        "Identify unusual spikes, failures, or unexpected behavior using metric thresholds."
    },
    {
      label: "Generate Dashboards",
      icon: "📈",
      detail:
        "Visualize important metrics through charts and dashboards for operational visibility."
    },
    {
      label: "Optimize Performance",
      icon: "⚙️",
      detail:
        "Use metric insights to improve reliability, efficiency, and user experience."
    }
  ],

  code: ""
},
{
  id: "langfuse",
  category: "Observability",
  title: "Langfuse",
  difficulty: "Intermediate",
  time: "~12 min",
  description:
    "Learn how Langfuse provides observability for LLM applications by tracking prompts, traces, token usage, costs, evaluations, and user feedback to improve AI Agent performance.",

  tags: [
    "langfuse",
    "observability",
    "tracing",
    "prompt management",
    "evaluation",
    "cost tracking",
    "llmops"
  ],

  concept: Langfuse,

  steps: [
    {
      label: "Capture Traces",
      icon: "🔍",
      detail:
        "Track every request, reasoning step, tool invocation, and response generated by the AI Agent."
    },
    {
      label: "Monitor Prompts",
      icon: "💬",
      detail:
        "Record prompts, model inputs, and outputs to analyze prompt quality and model behavior."
    },
    {
      label: "Measure Usage",
      icon: "📊",
      detail:
        "Collect metrics such as token consumption, latency, request volume, and API costs."
    },
    {
      label: "Evaluate Responses",
      icon: "⭐",
      detail:
        "Assess response quality using automated evaluations, human feedback, and custom scoring methods."
    },
    {
      label: "Debug Workflows",
      icon: "🛠️",
      detail:
        "Investigate failures, identify bottlenecks, and analyze execution traces for troubleshooting."
    },
    {
      label: "Optimize AI Systems",
      icon: "📈",
      detail:
        "Use observability insights to improve prompts, workflows, model selection, and production performance."
    }
  ],

  code: ""
},

{
  id: "langsmith",
  category: "Observability",
  title: "LangSmith",
  difficulty: "Intermediate",
  time: "~12 min",
  description:
    "Learn how LangSmith helps build, debug, evaluate, and monitor AI Agents by providing execution tracing, prompt inspection, testing, evaluation, and production observability.",

  tags: [
    "langsmith",
    "langchain",
    "observability",
    "tracing",
    "evaluation",
    "debugging",
    "llmops"
  ],

  concept: LangSmith,

  steps: [
    {
      label: "Capture Executions",
      icon: "📥",
      detail:
        "Record every workflow execution including prompts, model responses, tool calls, chains, and agent interactions."
    },
    {
      label: "Visualize Traces",
      icon: "🔗",
      detail:
        "View end-to-end execution traces to understand how the AI Agent processes requests and makes decisions."
    },
    {
      label: "Evaluate Responses",
      icon: "📊",
      detail:
        "Measure response quality using automated evaluations, custom metrics, and human feedback."
    },
    {
      label: "Debug Workflows",
      icon: "🐞",
      detail:
        "Identify prompt issues, reasoning failures, tool errors, and workflow bottlenecks through detailed execution analysis."
    },
    {
      label: "Monitor Production",
      icon: "📈",
      detail:
        "Track latency, failures, token usage, user interactions, and overall application performance in production."
    },
    {
      label: "Optimize Applications",
      icon: "⚙️",
      detail:
        "Improve prompts, workflows, retrieval pipelines, and agent behavior using insights collected from LangSmith."
    }
  ],

  code: ""
},
{
  id: "opentelemetry",
  category: "Observability",
  title: "OpenTelemetry",
  difficulty: "Advanced",
  time: "~15 min",
  description:
    "Learn how OpenTelemetry provides a standard framework for collecting logs, metrics, and traces from AI Agents to monitor, debug, and optimize distributed AI applications.",

  tags: [
    "opentelemetry",
    "otel",
    "logging",
    "metrics",
    "tracing",
    "monitoring",
    "observability"
  ],

  concept: OpenTelemetry,

  steps: [
    {
      label: "Instrument Applications",
      icon: "🔧",
      detail:
        "Integrate OpenTelemetry SDKs into AI Agent applications to automatically collect telemetry data."
    },
    {
      label: "Collect Telemetry",
      icon: "📊",
      detail:
        "Capture logs, metrics, and traces from agent workflows, APIs, databases, and external services."
    },
    {
      label: "Export Data",
      icon: "📤",
      detail:
        "Send telemetry data to observability platforms such as Jaeger, Grafana, Prometheus, Azure Monitor, or Datadog."
    },
    {
      label: "Analyze Performance",
      icon: "🔍",
      detail:
        "Examine execution traces, latency, resource utilization, and system health to identify operational issues."
    },
    {
      label: "Detect Problems",
      icon: "🚨",
      detail:
        "Identify bottlenecks, failures, service interruptions, and abnormal system behavior using telemetry insights."
    },
    {
      label: "Optimize Operations",
      icon: "📈",
      detail:
        "Continuously improve application reliability, scalability, and performance using observability data."
    }
  ],

  code: ""
},

{
  id: "cost-tracking",
  category: "Observability",
  title: "Cost Tracking",
  difficulty: "Intermediate",
  time: "~12 min",
  description:
    "Learn how Cost Tracking helps monitor AI Agent expenses by measuring token usage, model inference costs, API consumption, infrastructure utilization, and overall operational spending.",

  tags: [
    "cost tracking",
    "token usage",
    "llm cost",
    "api cost",
    "monitoring",
    "observability",
    "optimization"
  ],

  concept: CostTracking,

  steps: [
    {
      label: "Track Resource Usage",
      icon: "📊",
      detail:
        "Monitor token consumption, model invocations, API requests, tool executions, compute resources, and storage utilization."
    },
    {
      label: "Measure Costs",
      icon: "💰",
      detail:
        "Calculate operational expenses associated with LLM inference, external services, cloud infrastructure, and supporting tools."
    },
    {
      label: "Identify Cost Drivers",
      icon: "🔍",
      detail:
        "Determine which prompts, models, workflows, or tools contribute the most to overall spending."
    },
    {
      label: "Analyze Trends",
      icon: "📈",
      detail:
        "Monitor cost patterns over time to identify unexpected spikes, budget overruns, or optimization opportunities."
    },
    {
      label: "Optimize Spending",
      icon: "⚙️",
      detail:
        "Reduce costs through prompt optimization, caching, efficient model selection, and workflow improvements."
    },
    {
      label: "Generate Reports",
      icon: "📝",
      detail:
        "Create dashboards and reports that provide visibility into operational costs for stakeholders and engineering teams."
    }
  ],

  code: ""
},
{
  id: "debugging",
  category: "Observability",
  title: "Debugging",
  difficulty: "Intermediate",
  time: "~12 min",
  description:
    "Learn how Debugging helps identify, investigate, and resolve issues in AI Agent workflows by analyzing logs, traces, prompts, tool calls, and execution results.",

  tags: [
    "debugging",
    "troubleshooting",
    "logs",
    "traces",
    "errors",
    "observability",
    "diagnostics"
  ],

  concept: Debugging,

  steps: [
    {
      label: "Detect the Issue",
      icon: "🚨",
      detail:
        "Identify incorrect responses, workflow failures, tool errors, performance issues, or unexpected agent behavior."
    },
    {
      label: "Collect Diagnostics",
      icon: "📋",
      detail:
        "Gather logs, traces, prompts, metrics, and execution details needed for troubleshooting."
    },
    {
      label: "Analyze Root Cause",
      icon: "🔍",
      detail:
        "Determine whether the issue originates from prompts, models, retrieval, tools, APIs, or infrastructure."
    },
    {
      label: "Apply Fixes",
      icon: "🛠️",
      detail:
        "Correct configurations, improve prompts, update workflows, or resolve integration problems."
    },
    {
      label: "Validate the Solution",
      icon: "✔️",
      detail:
        "Re-test the workflow to confirm that the issue has been resolved and no new problems have been introduced."
    },
    {
      label: "Document Learnings",
      icon: "📚",
      detail:
        "Record the root cause, resolution, and best practices to simplify future debugging efforts."
    }
  ],

  code: ""
},
{
  id: "production-monitoring",
  category: "Observability",
  title: "Production Monitoring",
  difficulty: "Advanced",
  time: "~15 min",
  description:
    "Learn how Production Monitoring continuously observes AI Agent health, performance, reliability, security, and user experience in live production environments.",

  tags: [
    "production monitoring",
    "monitoring",
    "operations",
    "alerts",
    "observability",
    "performance",
    "production"
  ],

  concept: ProductionMonitoring,

  steps: [
    {
      label: "Monitor System Health",
      icon: "❤️",
      detail:
        "Continuously monitor service availability, agent status, infrastructure health, and workflow execution."
    },
    {
      label: "Track Performance",
      icon: "📊",
      detail:
        "Measure latency, throughput, success rate, token usage, cost, and resource utilization in real time."
    },
    {
      label: "Detect Incidents",
      icon: "🚨",
      detail:
        "Identify failures, service degradation, security events, and abnormal agent behavior as they occur."
    },
    {
      label: "Generate Alerts",
      icon: "🔔",
      detail:
        "Notify operations teams when predefined thresholds, SLAs, or business rules are violated."
    },
    {
      label: "Investigate Problems",
      icon: "🔍",
      detail:
        "Use logs, traces, metrics, and dashboards to diagnose issues and determine their root causes."
    },
    {
      label: "Continuously Improve",
      icon: "📈",
      detail:
        "Use production insights to optimize reliability, scalability, security, cost, and overall AI Agent performance."
    }
  ],
  code: ""
},


];
export default function CWDPage() { 
  return ( 
    <CookbookApp 
      data={AgentObservability}
      title="AgentObservability Cookbook" 
      subtitle="Complete Workflow Design" 
      icon="🧩" 
      patternLabel="Topics" 
    /> 
  ); 
}