import { useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import Logging from "../assets/docs/AgentObservability/Logging.md?raw";
import Tracing from "../assets/docs/AgentObservability/Tracing.md?raw";
import Metrics from "../assets/docs/AgentObservability/Metrics.md?raw";
import Monitoring from "../assets/docs/AgentObservability/Monitoring.md?raw";
import Langfuse from "../assets/docs/AgentObservability/Langfuse.md?raw";
import LangSmith from "../assets/docs/AgentObservability/LangSmith.md?raw";
import OpenTelemetry from "../assets/docs/AgentObservability/OpenTelemetry.md?raw";
import CostTracking from "../assets/docs/AgentObservability/CostTracking.md?raw";
import Debugging from "../assets/docs/AgentObservability/Debugging.md?raw";
import ProductionMonitoring from "../assets/docs/AgentObservability/ProductionMonitoring.md?raw";

const AgentObservability=[
{
  id: "logging",
  category: "Observability",
  title: "Logging",
  difficulty: "Beginner",
  time: "~10 min",
  description:
    "Learn how logging captures AI Agent events, tool executions, errors, and workflow activities to simplify debugging, auditing, and system analysis.",

  tags: [
    "logging",
    "logs",
    "debugging",
    "monitoring",
    "events",
    "audit",
    "observability"
  ],

  concept: Logging,

  steps: [
    {
      label: "Capture Events",
      icon: "📝",
      detail:
        "Record important events such as user requests, agent decisions, tool calls, and workflow execution."
    },
    {
      label: "Store Logs",
      icon: "💾",
      detail:
        "Save logs in a centralized location for future analysis and auditing."
    },
    {
      label: "Track Errors",
      icon: "⚠️",
      detail:
        "Log failures, exceptions, retries, and unexpected behaviors during execution."
    },
    {
      label: "Analyze Activity",
      icon: "🔍",
      detail:
        "Review logs to understand execution flow and identify operational issues."
    },
    {
      label: "Support Debugging",
      icon: "🛠️",
      detail:
        "Use logs to diagnose problems and improve workflow reliability."
    },
    {
      label: "Maintain Audit Trail",
      icon: "📊",
      detail:
        "Keep historical records for compliance, governance, and production support."
    }
  ],

  code: ""
},
{
  id: "metrics",
  category: "Observability",
  title: "Metrics",
  difficulty: "Intermediate",
  time: "~10 min",
  description:
    "Learn how metrics quantify AI Agent performance by measuring response time, success rate, resource utilization, costs, and overall system health.",

  tags: [
    "metrics",
    "performance",
    "monitoring",
    "kpis",
    "analytics",
    "observability",
    "measurement"
  ],

  concept: Metrics,

  steps: [
    {
      label: "Define Metrics",
      icon: "📋",
      detail:
        "Identify key performance indicators such as latency, throughput, success rate, token usage, and cost."
    },
    {
      label: "Collect Data",
      icon: "📥",
      detail:
        "Gather metrics from agent executions, tool calls, APIs, and infrastructure components."
    },
    {
      label: "Analyze Trends",
      icon: "📊",
      detail:
        "Monitor changes in performance over time to identify improvements or degradation."
    },
    {
      label: "Detect Anomalies",
      icon: "🚨",
      detail:
        "Identify unusual spikes, failures, or unexpected behavior using metric thresholds."
    },
    {
      label: "Generate Dashboards",
      icon: "📈",
      detail:
        "Visualize important metrics through charts and dashboards for operational visibility."
    },
    {
      label: "Optimize Performance",
      icon: "⚙️",
      detail:
        "Use metric insights to improve reliability, efficiency, and user experience."
    }
  ],

  code: ""
},
{
  id: "langfuse",
  category: "Observability",
  title: "Langfuse",
  difficulty: "Intermediate",
  time: "~12 min",
  description:
    "Learn how Langfuse provides observability for LLM applications by tracking prompts, traces, token usage, costs, evaluations, and user feedback to improve AI Agent performance.",

  tags: [
    "langfuse",
    "observability",
    "tracing",
    "prompt management",
    "evaluation",
    "cost tracking",
    "llmops"
  ],

  concept: Langfuse,

  steps: [
    {
      label: "Capture Traces",
      icon: "🔍",
      detail:
        "Track every request, reasoning step, tool invocation, and response generated by the AI Agent."
    },
    {
      label: "Monitor Prompts",
      icon: "💬",
      detail:
        "Record prompts, model inputs, and outputs to analyze prompt quality and model behavior."
    },
    {
      label: "Measure Usage",
      icon: "📊",
      detail:
        "Collect metrics such as token consumption, latency, request volume, and API costs."
    },
    {
      label: "Evaluate Responses",
      icon: "⭐",
      detail:
        "Assess response quality using automated evaluations, human feedback, and custom scoring methods."
    },
    {
      label: "Debug Workflows",
      icon: "🛠️",
      detail:
        "Investigate failures, identify bottlenecks, and analyze execution traces for troubleshooting."
    },
    {
      label: "Optimize AI Systems",
      icon: "📈",
      detail:
        "Use observability insights to improve prompts, workflows, model selection, and production performance."
    }
  ],

  code: ""
},

{
  id: "langsmith",
  category: "Observability",
  title: "LangSmith",
  difficulty: "Intermediate",
  time: "~12 min",
  description:
    "Learn how LangSmith helps build, debug, evaluate, and monitor AI Agents by providing execution tracing, prompt inspection, testing, evaluation, and production observability.",

  tags: [
    "langsmith",
    "langchain",
    "observability",
    "tracing",
    "evaluation",
    "debugging",
    "llmops"
  ],

  concept: LangSmith,

  steps: [
    {
      label: "Capture Executions",
      icon: "📥",
      detail:
        "Record every workflow execution including prompts, model responses, tool calls, chains, and agent interactions."
    },
    {
      label: "Visualize Traces",
      icon: "🔗",
      detail:
        "View end-to-end execution traces to understand how the AI Agent processes requests and makes decisions."
    },
    {
      label: "Evaluate Responses",
      icon: "📊",
      detail:
        "Measure response quality using automated evaluations, custom metrics, and human feedback."
    },
    {
      label: "Debug Workflows",
      icon: "🐞",
      detail:
        "Identify prompt issues, reasoning failures, tool errors, and workflow bottlenecks through detailed execution analysis."
    },
    {
      label: "Monitor Production",
      icon: "📈",
      detail:
        "Track latency, failures, token usage, user interactions, and overall application performance in production."
    },
    {
      label: "Optimize Applications",
      icon: "⚙️",
      detail:
        "Improve prompts, workflows, retrieval pipelines, and agent behavior using insights collected from LangSmith."
    }
  ],

  code: ""
},
{
  id: "opentelemetry",
  category: "Observability",
  title: "OpenTelemetry",
  difficulty: "Advanced",
  time: "~15 min",
  description:
    "Learn how OpenTelemetry provides a standard framework for collecting logs, metrics, and traces from AI Agents to monitor, debug, and optimize distributed AI applications.",

  tags: [
    "opentelemetry",
    "otel",
    "logging",
    "metrics",
    "tracing",
    "monitoring",
    "observability"
  ],

  concept: OpenTelemetry,

  steps: [
    {
      label: "Instrument Applications",
      icon: "🔧",
      detail:
        "Integrate OpenTelemetry SDKs into AI Agent applications to automatically collect telemetry data."
    },
    {
      label: "Collect Telemetry",
      icon: "📊",
      detail:
        "Capture logs, metrics, and traces from agent workflows, APIs, databases, and external services."
    },
    {
      label: "Export Data",
      icon: "📤",
      detail:
        "Send telemetry data to observability platforms such as Jaeger, Grafana, Prometheus, Azure Monitor, or Datadog."
    },
    {
      label: "Analyze Performance",
      icon: "🔍",
      detail:
        "Examine execution traces, latency, resource utilization, and system health to identify operational issues."
    },
    {
      label: "Detect Problems",
      icon: "🚨",
      detail:
        "Identify bottlenecks, failures, service interruptions, and abnormal system behavior using telemetry insights."
    },
    {
      label: "Optimize Operations",
      icon: "📈",
      detail:
        "Continuously improve application reliability, scalability, and performance using observability data."
    }
  ],

  code: ""
},

{
  id: "cost-tracking",
  category: "Observability",
  title: "Cost Tracking",
  difficulty: "Intermediate",
  time: "~12 min",
  description:
    "Learn how Cost Tracking helps monitor AI Agent expenses by measuring token usage, model inference costs, API consumption, infrastructure utilization, and overall operational spending.",

  tags: [
    "cost tracking",
    "token usage",
    "llm cost",
    "api cost",
    "monitoring",
    "observability",
    "optimization"
  ],

  concept: CostTracking,

  steps: [
    {
      label: "Track Resource Usage",
      icon: "📊",
      detail:
        "Monitor token consumption, model invocations, API requests, tool executions, compute resources, and storage utilization."
    },
    {
      label: "Measure Costs",
      icon: "💰",
      detail:
        "Calculate operational expenses associated with LLM inference, external services, cloud infrastructure, and supporting tools."
    },
    {
      label: "Identify Cost Drivers",
      icon: "🔍",
      detail:
        "Determine which prompts, models, workflows, or tools contribute the most to overall spending."
    },
    {
      label: "Analyze Trends",
      icon: "📈",
      detail:
        "Monitor cost patterns over time to identify unexpected spikes, budget overruns, or optimization opportunities."
    },
    {
      label: "Optimize Spending",
      icon: "⚙️",
      detail:
        "Reduce costs through prompt optimization, caching, efficient model selection, and workflow improvements."
    },
    {
      label: "Generate Reports",
      icon: "📝",
      detail:
        "Create dashboards and reports that provide visibility into operational costs for stakeholders and engineering teams."
    }
  ],

  code: ""
},
{
  id: "debugging",
  category: "Observability",
  title: "Debugging",
  difficulty: "Intermediate",
  time: "~12 min",
  description:
    "Learn how Debugging helps identify, investigate, and resolve issues in AI Agent workflows by analyzing logs, traces, prompts, tool calls, and execution results.",

  tags: [
    "debugging",
    "troubleshooting",
    "logs",
    "traces",
    "errors",
    "observability",
    "diagnostics"
  ],

  concept: Debugging,

  steps: [
    {
      label: "Detect the Issue",
      icon: "🚨",
      detail:
        "Identify incorrect responses, workflow failures, tool errors, performance issues, or unexpected agent behavior."
    },
    {
      label: "Collect Diagnostics",
      icon: "📋",
      detail:
        "Gather logs, traces, prompts, metrics, and execution details needed for troubleshooting."
    },
    {
      label: "Analyze Root Cause",
      icon: "🔍",
      detail:
        "Determine whether the issue originates from prompts, models, retrieval, tools, APIs, or infrastructure."
    },
    {
      label: "Apply Fixes",
      icon: "🛠️",
      detail:
        "Correct configurations, improve prompts, update workflows, or resolve integration problems."
    },
    {
      label: "Validate the Solution",
      icon: "✔️",
      detail:
        "Re-test the workflow to confirm that the issue has been resolved and no new problems have been introduced."
    },
    {
      label: "Document Learnings",
      icon: "📚",
      detail:
        "Record the root cause, resolution, and best practices to simplify future debugging efforts."
    }
  ],

  code: ""
},
{
  id: "production-monitoring",
  category: "Observability",
  title: "Production Monitoring",
  difficulty: "Advanced",
  time: "~15 min",
  description:
    "Learn how Production Monitoring continuously observes AI Agent health, performance, reliability, security, and user experience in live production environments.",

  tags: [
    "production monitoring",
    "monitoring",
    "operations",
    "alerts",
    "observability",
    "performance",
    "production"
  ],

  concept: ProductionMonitoring,

  steps: [
    {
      label: "Monitor System Health",
      icon: "❤️",
      detail:
        "Continuously monitor service availability, agent status, infrastructure health, and workflow execution."
    },
    {
      label: "Track Performance",
      icon: "📊",
      detail:
        "Measure latency, throughput, success rate, token usage, cost, and resource utilization in real time."
    },
    {
      label: "Detect Incidents",
      icon: "🚨",
      detail:
        "Identify failures, service degradation, security events, and abnormal agent behavior as they occur."
    },
    {
      label: "Generate Alerts",
      icon: "🔔",
      detail:
        "Notify operations teams when predefined thresholds, SLAs, or business rules are violated."
    },
    {
      label: "Investigate Problems",
      icon: "🔍",
      detail:
        "Use logs, traces, metrics, and dashboards to diagnose issues and determine their root causes."
    },
    {
      label: "Continuously Improve",
      icon: "📈",
      detail:
        "Use production insights to optimize reliability, scalability, security, cost, and overall AI Agent performance."
    }
  ],
  code: ""
},


];
const CATEGORIES = ["All","Core Concepts", "Planning","Tools & Actions","Memory","Multi-Agent", "Advanced"];
const DIFFICULTIES = { Beginner: "#0F6E56", Intermediate: "#185FA5", Advanced: "#993C1D" };
const DIFFICULTY_BG = { Beginner: "#E1F5EE", Intermediate: "#E6F1FB", Advanced: "#FAECE7" };

function StepFlow({ steps }) {
    const [active, setActive] = useState(null);
    return (
    <div style={{ marginTop: 16 }}>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center" }}>
        {steps.map((step, i) => (
            <div key={i} style={{ display: "flex", alignItems: "center", gap: 6 }}>
            <button
                onClick={() => setActive(active === i ? null : i)}
                style={{
                display: "flex", alignItems: "center", gap: 6, padding: "6px 12px",
                borderRadius: 20, border: active === i ? "1.5px solid #185FA5" : "0.5px solid var(--color-border-tertiary)",
                background: active === i ? "#E6F1FB" : "var(--color-background-primary)",
                color: active === i ? "#185FA5" : "var(--color-text-primary)",
                cursor: "pointer", fontSize: 13, fontWeight: active === i ? 500 : 400,
                transition: "all 0.15s",
                }}
            >
                <span>{step.icon}</span>
                <span>{step.label}</span>
            </button>
            {i < steps.length - 1 && (
                <span style={{ color: "var(--color-text-tertiary)", fontSize: 12 }}>→</span>
            )}
            </div>
        ))}
        </div>
        {active !== null && (
        <div style={{
            marginTop: 10, padding: "10px 14px", borderRadius: 8,
            background: "var(--color-background-secondary)",
            border: "0.5px solid var(--color-border-tertiary)",
            fontSize: 13, color: "var(--color-text-secondary)", lineHeight: 1.6,
        }}>
            <span style={{ fontWeight: 500, color: "var(--color-text-primary)" }}>{steps[active].label}: </span>
            {steps[active].detail}
        </div>
        )}
    </div>
    );
}


function ContentViewer({ content }) {
    return (
    <div className="prose max-w-none h-[75vh] overflow-y-auto p-6">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
        {content}
        </ReactMarkdown>
    </div>
    );
}

function CodeBlock({ code }) {
    const [copied, setCopied] = useState(false);
    const copy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
    };
    return (
    <div style={{ position: "relative", marginTop: 16 }}>
        <button
        onClick={copy}
        style={{
            position: "absolute", top: 8, right: 8, padding: "4px 10px",
            borderRadius: 6, border: "0.5px solid var(--color-border-secondary)",
            background: "var(--color-background-secondary)", cursor: "pointer",
            fontSize: 12, color: "var(--color-text-secondary)", zIndex: 1,
        }}
        >
        {copied ? "✓ Copied" : "Copy"}
        </button>
        <pre style={{
        margin: 0, padding: "14px 16px", borderRadius: 10, overflowX: "auto",
        background: "var(--color-background-secondary)",
        border: "0.5px solid var(--color-border-tertiary)",
        fontSize: 12, lineHeight: 1.65, fontFamily: "var(--font-mono)",
        color: "var(--color-text-primary)", whiteSpace: "pre",
        }}>
        <code>{code}</code>
        </pre>
    </div>
    );
}

function RecipeCard({ recipe, onSelect, selected }) {
    return (
    <div
        onClick={() => onSelect(recipe)}
        style={{
        padding: "16px 18px", borderRadius: 12, cursor: "pointer",
        border: selected ? "1.5px solid #185FA5" : "0.5px solid var(--color-border-tertiary)",
        background: selected ? "#061320" : "var(--color-background-primary)",
        transition: "all 0.15s",
        }}
    >
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 6 }}>
        <span style={{ fontSize: 13, color: "var(--color-text-secondary)", fontWeight: 400 }}>
            {recipe.category}
        </span>
        <span style={{
            fontSize: 11, padding: "2px 8px", borderRadius: 20, fontWeight: 500,
            background: DIFFICULTY_BG[recipe.difficulty], color: DIFFICULTIES[recipe.difficulty],
        }}>
            {recipe.difficulty}
        </span>
        </div>
        <div style={{ fontWeight: 500, fontSize: 15, marginBottom: 4, color: "var(--color-text-primary)" }}>
        {recipe.title}
        </div>
        <div style={{ fontSize: 13, color: "var(--color-text-secondary)", lineHeight: 1.5 }}>
        {recipe.description}
        </div>
        <div style={{ marginTop: 10, display: "flex", gap: 6, flexWrap: "wrap" }}>
        {recipe.tags.map((t) => (
            <span key={t} style={{
            fontSize: 11, padding: "2px 8px", borderRadius: 20,
            background: "var(--color-background-tertiary)",
            color: "var(--color-text-secondary)", border: "0.5px solid var(--color-border-tertiary)",
            }}>
            {t}
            </span>
        ))}
        </div>
    </div>
    );
}

function RecipeDetail({ recipe }) {
    const [tab, setTab] = useState("steps");
    return (
    <div style={{ padding: "24px", borderRadius: 14, background: "var(--color-background-primary)", border: "0.5px solid var(--color-border-tertiary)" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 4 }}>
        <div>
            <span style={{ fontSize: 12, color: "var(--color-text-tertiary)" }}>{recipe.category}</span>
            <h2 style={{ margin: "4px 0 6px", fontSize: 22, fontWeight: 500 }}>{recipe.title}</h2>
        </div>
        <div style={{ display: "flex", gap: 8, alignItems: "center", paddingTop: 4 }}>
            <span style={{
            fontSize: 12, padding: "3px 10px", borderRadius: 20, fontWeight: 500,
            background: DIFFICULTY_BG[recipe.difficulty], color: DIFFICULTIES[recipe.difficulty],
            }}>{recipe.difficulty}</span>
            <span style={{ fontSize: 12, color: "var(--color-text-tertiary)" }}>⏱ {recipe.time}</span>
        </div>
        </div>
        <p style={{ margin: "0 0 20px", color: "var(--color-text-secondary)", fontSize: 14, lineHeight: 1.6 }}>
        {recipe.description}
        </p>

        <div style={{ display: "flex", gap: 4, marginBottom: 18, borderBottom: "0.5px solid var(--color-border-tertiary)", paddingBottom: 0 }}>
        {["steps", "code", "concept"].map((t) => (
            <button
            key={t}
            onClick={() => setTab(t)}
            style={{
                padding: "8px 16px", border: "none", background: "none", cursor: "pointer",
                fontSize: 14, fontWeight: tab === t ? 500 : 400,
                color: tab === t ? "var(--color-text-primary)" : "var(--color-text-secondary)",
                borderBottom: tab === t ? "2px solid #185FA5" : "2px solid transparent",
                marginBottom: -1, transition: "all 0.12s",
            }}
            >
            {t === "steps" ? "Pipeline Steps" : t === "code" ? "Code" : "Concept"}
            </button>
        ))}
        </div>
        
        {tab === "steps" && <StepFlow steps={recipe.steps} />}
        {tab === "code" && <CodeBlock code={recipe.code} />}
        {tab === "concept" && <ContentViewer content={recipe.concept} />}
    </div>
    );
}

function Sidebar({ recipes, selected, onSelect, category, setCategory, search, setSearch }) {
    const filtered = recipes.filter((r) => {
    const matchCat = category === "All" || r.category === category;
    const matchSearch = r.title.toLowerCase().includes(search.toLowerCase()) ||
        r.tags.some((t) => t.toLowerCase().includes(search.toLowerCase()));
    return matchCat && matchSearch;
    });

    return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%", gap: 0 }}>
        <div style={{ padding: "0 0 16px" }}>
        <input
            type="text"
            placeholder="Search recipes…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            style={{
            width: "100%", boxSizing: "border-box", padding: "8px 12px",
            borderRadius: 8, border: "0.5px solid var(--color-border-secondary)",
            background: "var(--color-background-secondary)",
            color: "var(--color-text-primary)", fontSize: 13,
            }}
        />
        </div>
        <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 16 }}>
        {CATEGORIES.map((c) => (
            <button
            key={c}
            onClick={() => setCategory(c)}
            style={{
                padding: "4px 12px", borderRadius: 20, fontSize: 12, cursor: "pointer",
                border: category === c ? "1.5px solid #185FA5" : "0.5px solid var(--color-border-tertiary)",
                background: category === c ? "#E6F1FB" : "var(--color-background-primary)",
                color: category === c ? "#185FA5" : "var(--color-text-secondary)",
                fontWeight: category === c ? 500 : 400,
            }}
            >
            {c}
            </button>
        ))}
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: 10, overflowY: "auto", flex: 1 }}>
        {filtered.length === 0 ? (
            <div style={{ color: "var(--color-text-tertiary)", fontSize: 13, padding: "12px 0" }}>No recipes found.</div>
        ) : filtered.map((r) => (
            <RecipeCard key={r.id} recipe={r} onSelect={onSelect} selected={selected?.id === r.id} />
        ))}
        </div>
    </div>
    );
}

function Header() {
    return (
    <div style={{
        padding: "20px 32px 16px",
        borderBottom: "0.5px solid var(--color-border-tertiary)",
        display: "flex", alignItems: "center", gap: 16,
    }}>
        <div style={{
        width: 40, height: 40, borderRadius: 10,
        background: "#E6F1FB", display: "flex", alignItems: "center", justifyContent: "center",
        fontSize: 20,
        }}>
        📚
        </div>
        <div>
        <h1 style={{ margin: 0, fontSize: 20, fontWeight: 500, letterSpacing: "-0.3px" }}>AgenticAI Cookbook</h1>
        <p style={{ margin: 0, fontSize: 13, color: "var(--color-text-secondary)" }}>
            End-to-end Agentic AI   </p>
        </div>
        <div style={{ marginLeft: "auto", display: "flex", gap: 20 }}>
        {[
            { label: "Recipes", value: AgentObservability.length },
            { label: "Patterns", value: CATEGORIES.length - 1 },
        ].map(({ label, value }) => (
            <div key={label} style={{ textAlign: "center" }}>
            <div style={{ fontSize: 18, fontWeight: 500 }}>{value}</div>
            <div style={{ fontSize: 11, color: "var(--color-text-tertiary)" }}>{label}</div>
            </div>
        ))}
        </div>
    </div>
    );
}

export default function App() {
    const [selected, setSelected] = useState(AgentObservability[0]);
    const [category, setCategory] = useState("All");
    const [search, setSearch] = useState("");

    return (
    <div style={{
        display: "flex", flexDirection: "column",
        height: "100vh", fontFamily: "var(--font-sans, system-ui, sans-serif)",
        // background: "var(--color-background-tertiary, radial-gradient(circle at top, #0f172a, #020617);)",
        background: "var(--color-background-tertiary, radial-gradient(circle at top, #0f172a, #020617);)",
        color: "var(--color-text-primary)",
    }}>
        <Header />
        <div style={{ display: "flex", flex: 1, overflow: "hidden" }}>
        <div style={{
            width: 320, minWidth: 260, padding: "20px 20px",
            borderRight: "0.5px solid var(--color-border-tertiary)",
            background: "var(--color-background-primary)",
            overflowY: "auto",
        }}>
            <Sidebar
            recipes={AgentObservability}
            selected={selected}
            onSelect={setSelected}
            category={category}
            setCategory={setCategory}
            search={search}
            setSearch={setSearch}
            />
        </div>
        <div style={{ flex: 1, overflowY: "auto", padding: "24px 28px" }}>
            {selected ? (
            <RecipeDetail recipe={selected} />
            ) : (
            <div style={{ color: "var(--color-text-tertiary)", padding: 40, textAlign: "center" }}>
                Select a recipe to get started
            </div>
            )}
        </div>
        </div>
    </div>
    );
}
